import React, { useState, useEffect } from 'react';
import { apiRequest } from '../utils/api';
import {
  FileSpreadsheet,
  Search,
  Truck,
  Eye,
  RefreshCw,
  FileText,
  User,
  Calendar,
  CheckCircle2
} from 'lucide-react';
import '../employee/sales/SalesViews.css';
import './LogisticsPortal.css';

export default function LogisticsDeliveryNotesView({ currentUser, searchQuery }) {
  const [deliveryNotes, setDeliveryNotes] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState(searchQuery || '');

  // Synchronize with header search
  useEffect(() => {
    if (searchQuery !== undefined && searchQuery !== search) {
      setSearch(searchQuery);
    }
  }, [searchQuery]);

  const fetchDeliveryNotes = async () => {
    setLoading(true);
    try {
      const { response, data } = await apiRequest('/api/logistics/delivery-notes');
      if (response.ok && data.success) {
        setDeliveryNotes(data.data || []);
      }
    } catch (err) {
      console.error('[Fetch Logistics Delivery Notes Error]:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDeliveryNotes();
  }, []);

  const filtered = deliveryNotes.filter(dn => {
    if (!search.trim()) return true;
    const term = search.toLowerCase();
    const dnNum = (dn.deliveryNoteNumber || dn.deliveryNumber || '').toLowerCase();
    const soNum = (dn.salesOrderNumber || dn.salesOrder?.orderNumber || dn.sourceDocument || '').toLowerCase();
    const cust = (dn.clientName || '').toLowerCase();
    const sp = (dn.salePerson || dn.salesPerson?.fullName || '').toLowerCase();
    const shp = (dn.shipmentNumber || dn.shipmentId?.shipmentId || '').toLowerCase();
    return dnNum.includes(term) || soNum.includes(term) || cust.includes(term) || sp.includes(term) || shp.includes(term);
  });

  return (
    <div className="sv-container">
      {/* Header Bar */}
      <div className="sv-header">
        <div>
          <h2 className="sv-title">
            <FileSpreadsheet size={22} color="#2563EB" /> Blue File Delivery Notes
          </h2>
          <p className="sv-subtitle">
            Official delivery notes generated by Support for imported Blue File shipments
          </p>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <span
            style={{
              padding: '4px 12px',
              borderRadius: '20px',
              fontSize: '0.8rem',
              fontWeight: 700,
              backgroundColor: '#EFF6FF',
              color: '#1D4ED8',
              border: '1px solid #BFDBFE'
            }}
          >
            {filtered.length} Delivery Notes
          </span>
        </div>
      </div>

      {/* Search & Filter Header */}
      <div className="sv-filters">
        <div className="sv-search-box" style={{ flex: 1, maxWidth: '440px' }}>
          <Search size={16} color="#94A3B8" />
          <input
            type="text"
            placeholder="Search Delivery Note #, Sales Order, Customer, Sales Person..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="sv-search-input"
          />
          {search && (
            <button
              type="button"
              onClick={() => setSearch('')}
              style={{ background: 'none', border: 'none', color: '#94A3B8', cursor: 'pointer', fontSize: '0.8rem' }}
            >
              Clear
            </button>
          )}
        </div>

        <button
          onClick={fetchDeliveryNotes}
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: '6px',
            padding: '8px 14px',
            borderRadius: '8px',
            border: '1px solid #CBD5E1',
            background: '#FFFFFF',
            color: '#334155',
            fontSize: '0.82rem',
            fontWeight: 600,
            cursor: 'pointer'
          }}
          title="Reload delivery notes"
        >
          <RefreshCw size={14} className={loading ? 'logistics-spin' : ''} /> Refresh
        </button>
      </div>

      <div className="sv-card" style={{ background: '#FFFFFF', borderRadius: '14px', border: '1px solid #E2E8F0', overflow: 'hidden' }}>
        <div className="sv-table-wrap">
          {loading ? (
            <div style={{ textAlign: 'center', padding: '48px', color: '#64748B' }}>
              <RefreshCw size={24} className="logistics-spin" />
              <p style={{ marginTop: '10px', fontSize: '0.88rem' }}>Loading delivery notes from database...</p>
            </div>
          ) : filtered.length > 0 ? (
            <table className="sv-table" style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left', fontSize: '0.85rem' }}>
              <thead>
                <tr style={{ background: '#F8FAFC', borderBottom: '1px solid #E2E8F0' }}>
                  <th style={{ padding: '12px 16px', minWidth: '140px', color: '#64748B', fontWeight: 700, textTransform: 'uppercase', fontSize: '0.75rem' }}>Delivery Note #</th>
                  <th style={{ padding: '12px 16px', minWidth: '130px', color: '#64748B', fontWeight: 700, textTransform: 'uppercase', fontSize: '0.75rem' }}>Sales Order #</th>
                  <th style={{ padding: '12px 16px', minWidth: '140px', color: '#64748B', fontWeight: 700, textTransform: 'uppercase', fontSize: '0.75rem' }}>Sales Person</th>
                  <th style={{ padding: '12px 16px', minWidth: '140px', color: '#64748B', fontWeight: 700, textTransform: 'uppercase', fontSize: '0.75rem' }}>Customer</th>
                  <th style={{ padding: '12px 16px', minWidth: '150px', color: '#64748B', fontWeight: 700, textTransform: 'uppercase', fontSize: '0.75rem' }}>Shipment / Flight #</th>
                  <th style={{ padding: '12px 16px', minWidth: '130px', color: '#64748B', fontWeight: 700, textTransform: 'uppercase', fontSize: '0.75rem' }}>Supplier PO #</th>
                  <th style={{ padding: '12px 16px', minWidth: '110px', color: '#64748B', fontWeight: 700, textTransform: 'uppercase', fontSize: '0.75rem' }}>Status</th>
                  <th style={{ padding: '12px 16px', minWidth: '110px', color: '#64748B', fontWeight: 700, textTransform: 'uppercase', fontSize: '0.75rem' }}>Date</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((dn) => (
                  <tr key={dn._id} style={{ borderBottom: '1px solid #F1F5F9' }}>
                    <td style={{ padding: '14px 16px' }}>
                      <span style={{
                        fontFamily: 'monospace',
                        fontWeight: 700,
                        fontSize: '0.82rem',
                        background: '#F1F5F9',
                        color: '#0F172A',
                        padding: '3px 8px',
                        borderRadius: '6px',
                        border: '1px solid #E2E8F0',
                        display: 'inline-block'
                      }}>
                        {dn.deliveryNoteNumber || dn.deliveryNumber}
                      </span>
                    </td>
                    <td style={{ padding: '14px 16px' }}>
                      <span style={{ fontWeight: 700, color: '#1E293B', display: 'block' }}>
                        {dn.salesOrderNumber || dn.sourceDocument || '—'}
                      </span>
                    </td>
                    <td style={{ padding: '14px 16px' }}>
                      <span style={{ color: '#0F172A', fontWeight: 600 }}>
                        {dn.salePerson || dn.salesPerson?.fullName || 'Sales Person'}
                      </span>
                    </td>
                    <td style={{ padding: '14px 16px', color: '#334155' }}>{dn.clientName || '—'}</td>
                    <td style={{ padding: '14px 16px' }}>
                      <span style={{ fontFamily: 'monospace', color: '#2563EB', fontWeight: 700 }}>
                        {dn.shipmentNumber || dn.shipmentId?.shipmentId || 'Imported'}
                      </span>
                    </td>
                    <td style={{ padding: '14px 16px' }}>
                      <span style={{ fontSize: '0.82rem', color: '#475569' }}>
                        {dn.supplierPoNumber || dn.supplierPO?.poNumber || '—'}
                      </span>
                    </td>
                    <td style={{ padding: '14px 16px' }}>
                      <span
                        style={{
                          display: 'inline-block',
                          padding: '3px 9px',
                          borderRadius: '20px',
                          fontSize: '0.74rem',
                          fontWeight: 700,
                          backgroundColor: '#DCFCE7',
                          color: '#15803D'
                        }}
                      >
                        {dn.status || 'Ready'}
                      </span>
                    </td>
                    <td style={{ padding: '14px 16px', fontSize: '0.82rem', color: '#64748B' }}>
                      {new Date(dn.createdAt).toLocaleDateString()}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          ) : (
            <div style={{ textAlign: 'center', padding: '56px 24px', color: '#64748B' }}>
              <FileSpreadsheet size={44} color="#94A3B8" style={{ marginBottom: '10px' }} />
              <h4 style={{ margin: '4px 0 6px 0', fontSize: '1.05rem', fontWeight: 700, color: '#1E293B' }}>
                No Delivery Notes Found
              </h4>
              <p style={{ margin: 0, fontSize: '0.86rem', color: '#94A3B8', maxWidth: '440px', marginInline: 'auto' }}>
                Delivery notes issued by Support for Blue File shipments will appear here automatically.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
